[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-native-tls"]}
serde = { version = "1.0", features = ["derive"]}
tokio = { version = "1", features = ["full"]}
